"""empty message

Revision ID: 9563330ae30d
Revises: f72862fbbff9
Create Date: 2023-08-13 01:09:25.141805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9563330ae30d'
down_revision = 'f72862fbbff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lucky_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lucky_number')

    # ### end Alembic commands ###
